# tasks file for nagios-plugin-percona
---
- name: configure | copy certificate files
  copy:
    src: "{{ item.value.src }}"
    dest: "{{ item.value.dest }}"
    owner: "{{ item.value.owner | default('root') }}"
    group: "{{ item.value.group | default('nagios') }}"
    mode: "{{ item.value.mode | default('0640') }}"
  with_dict: nagios_plugin_percona_ssl_map
  tags:
    - nagios-plugin-percona-configure-copy-certificate-files

- name: configure | update (user) configuration file(s)
  template:
    src: root/.my.cnf.j2
    dest: "{{ item.dest | default('~' + item.owner + '/.my.cnf') }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group | default(item.owner) }}"
    mode: "{{ item.mode | default('0600') }}"
  with_items: nagios_plugin_percona_my_cnf_files
  tags:
    - nagios-plugin-percona-configure-user-my-cnf
