# tasks file for nagios-plugin-percona
---
- block:

    - name: install | dependencies
      apt:
        name: "{{ nagios_plugin_percona_dependencies }}"
        state: "{{ apt_install_state | default('latest') }}"
      tags:
        - nagios-plugin-percona-install-dependencies

  when: nagios_plugin_percona_package_path_src is not defined

- block:

    - name: install | dependencies
      apt:
        name:
          # To prevent: There is no member named 'control'
          - xz-utils
        state: "{{ apt_install_state | default('latest') }}"
      tags:
        - nagios-plugin-percona-install-dependencies

    - name: install | create (download) directory
      file:
        path: "{{ nagios_plugin_percona_package_path_dest }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      tags:
        - nagios-plugin-percona-install-download
        - nagios-plugin-percona-install-download-directory

    - name: install | copy deb
      copy:
        src: "{{ nagios_plugin_percona_package_path_src }}"
        dest: "{{ nagios_plugin_percona_package_path_dest }}/{{ nagios_plugin_percona_package_path_src | basename }}"
        owner: root
        group: root
        mode: 0644
      tags:
        - nagios-plugin-percona-install-download
        - nagios-plugin-percona-install-download-deb

    - name: install | install deb
      apt:
        update_cache: true
        cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
        deb: "{{ nagios_plugin_percona_package_path_dest }}/{{ nagios_plugin_percona_package_path_src | basename }}"
      tags:
        - nagios-plugin-percona-install-install
        - nagios-plugin-percona-install-install-deb

  when: nagios_plugin_percona_package_path_src is defined

- name: install | additional
  apt:
    name: "{{ nagios_plugin_percona_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - nagios-plugin-percona-install-additional

- name: install | get plugins in "wrong" directory
  shell: >
    ls -1dt /usr/lib64/nagios/plugins/*
  register: _plugins_in_wrong_directory
  changed_when: false
  tags:
    - nagios-plugin-percona-get-plugins

- name: install | create directory
  file:
    path: /usr/lib/nagios/plugins
    state: directory
    mode: 0755
  tags:
    - nagios-plugin-percona-create-directory

- name: install | create symlinks in correct directory
  file:
    src: "{{ item }}"
    dest: "/usr/lib/nagios/plugins/{{ item | basename }}"
    state: link
    force: true
  with_items: "{{ _plugins_in_wrong_directory.stdout_lines }}"
  tags:
    - nagios-plugin-percona-create-symlinks
