# tasks file for nagios-plugin-percona
---
- name: install | dependencies
  apt:
    name: "{{ nagios_plugin_percona_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - nagios-plugin-percona-install-dependencies

- name: install | additional
  apt:
    name: "{{ nagios_plugin_percona_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - nagios-plugin-percona-install-additional

- name: install | get plugins in "wrong" directory
  shell: >
    ls -1dt /usr/lib64/nagios/plugins/*
  register: _plugins_in_wrong_directory
  changed_when: false
  tags:
    - nagios-plugin-percona-get-plugins

- name: install | create directory
  file:
    path: /usr/lib/nagios/plugins
    state: directory
    mode: 0755
  tags:
    - nagios-plugin-percona-create-directory

- name: install | create symlinks in correct directory
  file:
    src: "{{ item }}"
    dest: "/usr/lib/nagios/plugins/{{ item | basename }}"
    state: link
    force: true
  with_items: "{{ _plugins_in_wrong_directory.stdout_lines }}"
  tags:
    - nagios-plugin-percona-create-symlinks
