# tasks file
---
- ansible.builtin.import_tasks: repository.yml
  when: nagios_plugin_percona_package_path_src is not defined
  tags:
    - configuration
    - nagios-plugin-percona
    - nagios-plugin-percona-repository

- ansible.builtin.import_tasks: install.yml
  tags:
    - configuration
    - nagios-plugin-percona
    - nagios-plugin-percona-install
