# tasks file
---
- name: repository | install | dependencies (pre)
  apt:
    name: "{{ nagios_plugin_percona_dependencies_pre }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - nagios-plugin-percona-repository-install
    - nagios-plugin-percona-repository-install-dependencies

- name: repository | add public key
  apt_key:
    id: 9334A25F8507EFA5
    keyserver: keyserver.ubuntu.com
    state: present
  tags:
    - nagios-plugin-percona-repository-public-key

- name: repository | add
  apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: present
    update_cache: true
    mode: 0644
  with_items: "{{ nagios_plugin_percona_repositories }}"
  tags:
    - nagios-plugin-percona-repository-add

- name: repository | apt-pin packages
  copy:
    src: etc/apt/preferences.d/00percona.pref
    dest: /etc/apt/preferences.d/00percona.pref
    owner: root
    group: root
    mode: 0644
  tags:
    - nagios-plugin-percona-repository-apt-pin
